import { IExerciseCatalog } from "../types/ExerciseCatalog";


export const DEFAULT_EXERCISES : IExerciseCatalog[] = [ 
    {
        id: "bench_press",
        name: "Жим штанги лёжа",
        tags: ["Грудь", "Трицепс","Плечи"],
        description: "Базовое упражнение для развития грудных мышц, трицепсов и передней дельты.",
        rating: 5,
        createdByUser: false,
    }, {
        id: "incline_bench",
        name: "Жим штанги на наклонной скамье",
        tags: ["Грудь", "Плечи", "Трицепс"],
        description: "Акцент на верх груди, хорошо развивает силу и массу.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "dips_chest",
        name: "Отжимания на брусьях (грудь)",
        tags: ["Грудь", "Трицепс", "Плечи"],
        description: "Отличное базовое упражнение на грудь с собственным весом.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "close_grip_bench",
        name: "Жим штанги узким хватом",
        tags: ["Трицепс", "Грудь"],
        description: "Базовое упражнение для трицепса с вовлечением груди.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "deadlift_classic",
        name: "Становая тяга (классика)",
        tags: ["Спина", "Ноги", "Кор"],
        description: "Классическая становая тяга с акцентом на спину.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "deadlift_sumo",
        name: "Становая тяга (сумо)",
        tags: ["Спина", "Ноги", "Кор"],
        description: "Становая тяга с широкой постановкой ног, меньше нагрузки на спину.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "barbell_row",
        name: "Тяга штанги в наклоне",
        tags: ["Спина"],
        description: "Базовое упражнение для толщины спины.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "seated_row",
        name: "Тяга горизонтального блока",
        tags: ["Спина"],
        description: "Контролируемая тяга для средней части спины.",
        rating: 4,
        createdByUser: false,
    },
   {
        id: "pull_up",
        name: "Подтягивания",
        tags: ["Спина", "Бицепс","Предплечья"],
        description: "Лучшее упражнение для ширины спины и силы рук.",
        rating: 5,
        createdByUser: false,
    }, {
        id: "lat_pulldown",
        name: "Тяга верхнего блока",
        tags: ["Спина"],
        description: "Отличная альтернатива подтягиваниям.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "lateral_raise",
        name: "Махи гантелей в стороны",
        tags: ["Плечи"],
        description: "Лучшее изолирующее упражнение на среднюю дельту.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "front_raise",
        name: "Махи гантелей перед собой",
        tags: ["Плечи"],
        description: "Изолирующее упражнение на переднюю дельту.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "rear_delt_fly",
        name: "Разведения на заднюю дельту",
        tags: ["Плечи", "Спина"],
        description: "Упражнение для баланса плечевого пояса.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "skull_crushers",
        name: "Французский жим лёжа",
        tags: ["Трицепс"],
        description: "Изолированное упражнение для трицепса.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "triceps_block",
        name: "Трицепс в кроссовере",
        tags: ["Трицепс"],
        description: "Изолированное упражнение для трицепса.",
        rating: 4,
        createdByUser: false,
    },
     
    {
        id: "incline_dumbbell_press",
        name: "Жим гантелей на наклонной скамье",
        tags: ["Грудь","Плечи", "Трицепс"],
        description: "Развивает грудь и трицепс.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "biceps_curl",
        name: "Подъём штанги на бицепс",
        tags: ["Предплечья", "Бицепс"],
        description: "Изолированное упражнение для бицепса.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "biceps_curl_dumbbells",
        name: "Подъём гантелей на бицепс",
        tags: ["Предплечья", "Бицепс"],
        description: "Изолированное упражнение для бицепса.",
        rating: 5,
        createdByUser: false,
    },
    {
        id: "biceps_curl_molot",
        name: "Молотки на бицепс",
        tags: ["Предплечья", "Бицепс"],
        description: "Изолированное упражнение для бицепса с акцентом на предплечья.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "leg_press",
        name: "Жим ногами",
        tags: ["Ноги"],
        description: "Безопасное упражнение для квадрицепсов.",
        rating: 4,
        createdByUser: false,
    },
    {
        id: "leg_extension",
        name: "Разгибание ног в тренажере",
        tags: ["Ноги"],
        description: "Безопасное упражнение для прокачки ног.",
        rating: 3,
        createdByUser: false,
    },
]